# Generated by Django 4.2.29 on 2026-05-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_quizquestion_quizresult_quizoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='default_format',
        ),
    ]
