# Generated by Django 4.2.29 on 2026-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_quizresult_default_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('video', models.FileField(help_text='MP4, 16:9', upload_to='about_videos/', verbose_name='Видеофайл')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': "Видео для страницы 'О нас'",
                'verbose_name_plural': "Видео для страницы 'О нас'",
                'ordering': ['order', 'id'],
            },
        ),
    ]
